name: Build S3AIR Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Compilar dependencias externas
        shell: cmd
        run: |
          cd framework\external
          build_externals_windows.bat

      - name: Compilar S3AIR
        shell: cmd
        run: |
          msbuild sonic3air.sln ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /m

      - name: Buscar ejecutables
        shell: powershell
        run: |
          Get-ChildItem -Path . -Filter *.exe -Recurse

      - name: Subir ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: S3AIR-Windows
          path: |
            **/*.exe
