name: Build Sonic 3 A.I.R. - Windows
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@main

      - name: Build external dependencies
        shell: cmd
        working-directory: framework/external
        run: |
          call build_externals_windows.bat

      - name: Build Mastering
        shell: cmd
        working-directory: Oxygen/sonic3air/___internal/mastering
        run: |
          call mastering_windows_64bit.bat

      - name: Upload build
        uses: actions/upload-artifact@main
        with:
          name: sonic3air-windows
          path: |
            **/*.exe
